#!/usr/bin/env bash

# Helper script that reset the Laravel database, clears the caches and regenerates helper documentation

pathStart=$PWD

cd /vagrant/laravel
php artisan route:cache
php artisan migrate:fresh
php artisan migrate
php artisan db:seed
composer dump-autoload
php artisan clear-compiled
php artisan ide-helper:generate
php artisan ide-helper:meta
php artisan ide-helper:models --write --reset
php artisan optimize
php artisan route:list

cd $pathStart
